# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'


stages:

- stage: Build
  jobs:
  - job: BuildJob

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        version: '6.0.x' # Cambia a la versión de .NET Core que estás utilizando

    - script: dotnet restore --configuration $(buildConfiguration)
      displayName: 'Restore Dependencies'

    - script: dotnet build --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Solution'

#- script: dotnet test --configuration $(buildConfiguration) --no-restore --collect "Code coverage"
#  displayName: 'Run Tests'